#* Backend Priority Order: Core, Aqua, Github, Package Manager (cargo, npm, pipx)

[tools]
#* Main
"github:asciinema/asciinema" = "3.2.1" # Used for generating cli demos
"cargo:nemasvg" = "0.2.0"              # Used for converting asciinema to animated SVGs for demos
"cargo:templatry" = "0.2.0"            # Used for generating config files
#* Linting
"aqua:jdx/hk" = "2.1.0"                    # Used for running linting, formatting & git hooks
"aqua:astral-sh/uv" = "0.12.17"            # Used for python (pipx) linting tools
"aqua:mikefarah/yq" = "4.53.6"             # Used for validating & formatting JSON & toml parsing
"aqua:tombi-toml/tombi" = "1.5.5"          # Used for validating & formatting TOML
"aqua:EmbarkStudios/cargo-deny" = "0.20.2" # Used for auditing dependencies (hk cargo deny step)
"aqua:rvben/rumdl" = "0.2.75"              # Used for linting & formatting markdown
"aqua:loeffel-io/ls-lint" = "2.3.1"        # Used for enforcing folder & file naming conventions
"aqua:lycheeverse/lychee" = "0.24.2"       # Used for checking for dead links
"aqua:google/yamlfmt" = "0.21.0"           # Used for formatting YAML
"github:zizmorcore/zizmor" = "v1.30.1"     # Used for statically analyzing github actions
"github:mongodb/kingfisher" = "v2.5.0"     # Used for checking for leaked credentials & secrets
"github:kucherenko/jscpd" = "v5.3.1"       # Used for detecting code duplication
"pipx:yamllint" = "1.38.0"                 # Used for linting YAML

[tools."http:flutter"]
version = "3.47.5"
version_expr = 'fromJSON(body).releases | filter({ #.channel == "stable" }) | map({ replace(#.version, "-stable", "") }) | sortVersions()'
checksum_expr = '"sha256:" + filter(fromJSON(body).releases, { #.archive endsWith filename })[0].sha256'
version_list_url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"

[tools."http:flutter".platforms]
macos-x64 = { url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_{{ version }}-stable.zip", checksum_url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json" }
macos-arm64 = { url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_{{ version }}-stable.zip", checksum_url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json" }
windows-x64 = { url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_{{ version }}-stable.zip", checksum_url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json" }
linux-x64 = { url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_{{ version }}-stable.tar.xz", checksum_url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json" }

[settings]
lockfile = true
