[global]
disable = ["MD013"]
exclude = ["**/CHANGELOG.md"]
extend-enable = ["MD060", "MD063", "MD070", "MD072", "MD073", "MD080", "MD082", "MD083", "MD084", "MD085", "MD087"]

[MD060]
loose-last-column = true

[MD063]
style = "title-case"
preserve-cased-words = true

[MD082]
allow-parent-headings = true

[MD083]
ignore-code-blocks = true

[MD084]
strict = true
